### ISSUE TITLE
Runway Configuration doesn´t need a time selection bar

### ISSUE THREAD

**Issue by fjcrabiffosse** [eurocontrol-swim/predicted-runway-ui#2]
Due to the new changes to the UI in the Runway Configuration prediction the selection of the time of arrival is done in the result screen and not before during the prediction request. This means the time selection slider is not useful anymore when requesting a prediction. Could be removed.

**Comment by antavelos** [comment]
fixed [3bab5e](https://github.com/eurocontrol-swim/predicted-runway-ui/commit/3bab5e2b288775f5460be2ee143d341f1b916252)
